### ISSUE TITLE
Bug: Doesn't work when spaces around fragment delimiter "::"

### ISSUE THREAD

**Issue by dhait** [BlackPepperSoftware/thymeleaf-fragment.js#5]
This doesn't work:

```
<div th:replace="fragments/header :: header">
```

But this does:

```
<div th:replace="fragments/header::header">
```

**Comment by markhobson** [comment]
Apologies for the delay in fixing this. We now trim whitespace within the fragment spec so the following should be equivalent:
* `<div th:replace="fragments/header::header">`
* `<div th:replace="fragments/header :: header">`
* `<div th:replace=" fragments/header :: header ">`
